name: CI

on:
  push:
    branches:
      - fork-master
    tags:
      - "*"
  pull_request:
    branches:
      - fork-master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.0'
        id: go

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        if: startsWith(github.ref, 'refs/tags/v') == false
        run: make build-image

      - name: Pull image
        if: startsWith(github.ref, 'refs/tags/v')
        run: make pull-image

      - name: Push image
        if: startsWith(github.ref, 'refs/tags/v') == false
        run: |
          make push-image

      - name: Promote image
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          make promote-image GITHUB_REF=$GITHUB_REF
